#############################################################################
# Makefile for building: BombDynasty.app/Contents/MacOS/BombDynasty
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  BombDynasty.pro
# Template: app
# Command: /Users/kitty/Applications/Qt/5.12.0/clang_64/bin/qmake -o Makefile BombDynasty.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers -I../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I../../Applications/Qt/5.12.0/clang_64/lib/QtNetwork.framework/Headers -I../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang -F/Users/kitty/Applications/Qt/5.12.0/clang_64/lib
QMAKE         = /Users/kitty/Applications/Qt/5.12.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/kitty/Applications/Qt/5.12.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/kitty/Applications/Qt/5.12.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BombDynasty1.0.0
DISTDIR = /Users/kitty/Downloads/bomb_dynasty-03_15/.tmp/BombDynasty1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/Users/kitty/Applications/Qt/5.12.0/clang_64/lib -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		welcomepage.cpp \
		bomb.cpp \
		player.cpp \
		graph.cpp qrc_res.cpp \
		moc_welcomepage.cpp \
		moc_gameframe2.cpp
OBJECTS       = main.o \
		welcomepage.o \
		bomb.o \
		player.o \
		graph.o \
		qrc_res.o \
		moc_welcomepage.o \
		moc_gameframe2.o
DIST          = icons/bomb+1.jpg \
		icons/freeze.jpg \
		icons/ghost.jpg \
		icons/powerup.jpg \
		icons/push.jpg \
		icons/reverse.jpg \
		icons/shield.jpg \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/uic.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		BombDynasty.pro welcomepage.h \
		bomb.h \
		player.h \
		gameframe2.h \
		icon.h \
		graph.h main.cpp \
		welcomepage.cpp \
		bomb.cpp \
		player.cpp \
		graph.cpp
QMAKE_TARGET  = BombDynasty
DESTDIR       = 
TARGET        = BombDynasty.app/Contents/MacOS/BombDynasty

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/kitty/Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BombDynasty.app/Contents/MacOS/BombDynasty: ui_welcomepage.h ui_gameframe2.h $(OBJECTS)  
	@test -d BombDynasty.app/Contents/MacOS/ || mkdir -p BombDynasty.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BombDynasty.pro ../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf ../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/uic.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../Applications/Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		BombDynasty.pro \
		res.qrc \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Applications/Qt/5.12.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile BombDynasty.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/qdevice.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/device_config.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/unix.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/mac.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/macx.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/qconfig.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/default_post.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qt.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/resources.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/moc.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/opengl.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/uic.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/yacc.prf:
../../Applications/Qt/5.12.0/clang_64/mkspecs/features/lex.prf:
BombDynasty.pro:
res.qrc:
../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../Applications/Qt/5.12.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BombDynasty.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

BombDynasty.app/Contents/PkgInfo: 
	@test -d BombDynasty.app/Contents || mkdir -p BombDynasty.app/Contents
	@$(DEL_FILE) BombDynasty.app/Contents/PkgInfo
	@echo "APPL????" > BombDynasty.app/Contents/PkgInfo
BombDynasty.app/Contents/Resources/empty.lproj: 
	@test -d BombDynasty.app/Contents/Resources || mkdir -p BombDynasty.app/Contents/Resources
	@touch BombDynasty.app/Contents/Resources/empty.lproj
	
BombDynasty.app/Contents/Info.plist: 
	@test -d BombDynasty.app/Contents || mkdir -p BombDynasty.app/Contents
	@$(DEL_FILE) BombDynasty.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,pic10c.BombDynasty,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},pic10c.BombDynasty,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,BombDynasty,g" -e "s,@LIBRARY@,BombDynasty,g" -e "s,\$${EXECUTABLE_NAME},BombDynasty,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang/Info.plist.app >BombDynasty.app/Contents/Info.plist

all: Makefile \
		BombDynasty.app/Contents/PkgInfo \
		BombDynasty.app/Contents/Resources/empty.lproj \
		BombDynasty.app/Contents/Info.plist BombDynasty.app/Contents/MacOS/BombDynasty

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Applications/Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents welcomepage.h bomb.h player.h gameframe2.h icon.h graph.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp welcomepage.cpp bomb.cpp player.cpp graph.cpp $(DISTDIR)/
	$(COPY_FILE) --parents welcomepage.ui gameframe2.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BombDynasty.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		../../Applications/Qt/5.12.0/clang_64/bin/rcc \
		sound_effects/icon.mp3 \
		sound_effects/mine.mp3 \
		sound_effects/explosion.mp3 \
		sound_effects/Five_Armies.mp3 \
		gamefield_graphics/IMG_0447.PNG \
		gamefield_graphics/bomb.png \
		gamefield_graphics/bombed.png \
		gamefield_graphics/background.png \
		gamefield_graphics/freezebg.png \
		gamefield_graphics/transparent.png \
		gamefield_graphics/wall.jpg \
		gamefield_graphics/minegraphics.png \
		gamefield_graphics/ribbons.png \
		gamefield_graphics/doubleplayerpic.jpg \
		gamefield_graphics/t.png \
		gamefield_graphics/Queen.png \
		gamefield_graphics/practicepic.jpg \
		gamefield_graphics/p1.PNG \
		gamefield_graphics/p2.PNG \
		gamefield_graphics/vbeffect.png \
		gamefield_graphics/gamefield.png \
		gamefield_graphics/hbeffect.png \
		gamefield_graphics/icons/mine.jpg \
		gamefield_graphics/icons/freeze.jpg \
		gamefield_graphics/icons/ghost.jpg \
		gamefield_graphics/icons/push.jpg \
		gamefield_graphics/icons/shield.jpg \
		gamefield_graphics/icons/powerup.jpg \
		gamefield_graphics/icons/bomb+1.jpg \
		gamefield_graphics/icons/reverse.jpg
	/Users/kitty/Applications/Qt/5.12.0/clang_64/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Applications/Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Applications/Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_welcomepage.cpp moc_gameframe2.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_welcomepage.cpp moc_gameframe2.cpp
moc_welcomepage.cpp: ../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		gameframe2.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPair \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpair.h \
		graph.h \
		icon.h \
		player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		welcomepage.h \
		moc_predefs.h \
		../../Applications/Qt/5.12.0/clang_64/bin/moc
	/Users/kitty/Applications/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/kitty/Downloads/bomb_dynasty-03_15/moc_predefs.h -I/Users/kitty/Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/kitty/Downloads/bomb_dynasty-03_15 -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtNetwork.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/kitty/Applications/Qt/5.12.0/clang_64/lib welcomepage.h -o moc_welcomepage.cpp

moc_gameframe2.cpp: ../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPair \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpair.h \
		graph.h \
		icon.h \
		player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		gameframe2.h \
		moc_predefs.h \
		../../Applications/Qt/5.12.0/clang_64/bin/moc
	/Users/kitty/Applications/Qt/5.12.0/clang_64/bin/moc $(DEFINES) --include /Users/kitty/Downloads/bomb_dynasty-03_15/moc_predefs.h -I/Users/kitty/Applications/Qt/5.12.0/clang_64/mkspecs/macx-clang -I/Users/kitty/Downloads/bomb_dynasty-03_15 -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtNetwork.framework/Headers -I/Users/kitty/Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/kitty/Applications/Qt/5.12.0/clang_64/lib gameframe2.h -o moc_gameframe2.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_welcomepage.h ui_gameframe2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_welcomepage.h ui_gameframe2.h
ui_welcomepage.h: welcomepage.ui \
		../../Applications/Qt/5.12.0/clang_64/bin/uic
	/Users/kitty/Applications/Qt/5.12.0/clang_64/bin/uic welcomepage.ui -o ui_welcomepage.h

ui_gameframe2.h: gameframe2.ui \
		../../Applications/Qt/5.12.0/clang_64/bin/uic
	/Users/kitty/Applications/Qt/5.12.0/clang_64/bin/uic gameframe2.ui -o ui_gameframe2.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp welcomepage.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		gameframe2.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPair \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpair.h \
		graph.h \
		icon.h \
		player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

welcomepage.o: welcomepage.cpp welcomepage.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QRadioButton \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPalette \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QStackedWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		gameframe2.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPair \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpair.h \
		graph.h \
		icon.h \
		player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		ui_welcomepage.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o welcomepage.o welcomepage.cpp

bomb.o: bomb.cpp bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		gameframe2.cpp \
		gameframe2.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QPair \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qpair.h \
		graph.h \
		icon.h \
		player.h \
		ui_gameframe2.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QString \
		../../Applications/Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o bomb.cpp

player.o: player.cpp player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

graph.o: graph.cpp graph.h \
		icon.h \
		player.h \
		bomb.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Applications/Qt/5.12.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Applications/Qt/5.12.0/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o graph.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_welcomepage.o: moc_welcomepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_welcomepage.o moc_welcomepage.cpp

moc_gameframe2.o: moc_gameframe2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameframe2.o moc_gameframe2.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/BombDynasty/bin || mkdir -p $(INSTALL_ROOT)/opt/BombDynasty/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/BombDynasty/bin/BombDynasty.app
	
	-$(QINSTALL) BombDynasty.app $(INSTALL_ROOT)/opt/BombDynasty/bin/BombDynasty.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/BombDynasty/bin/BombDynasty.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/BombDynasty/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

